<<<<<<< HEAD:src/VehicleModel.java

/**
 * @author Carson Allbee callbee
 *CIS175 - Fall 2021
 * Feb 28, 2022
 */
public class VehicleModel extends Vehicle{

	private String brand;
	private String model;
	private int mileage;
	private boolean newCondition;
	private boolean warrentyStatus;
	private int doorNumber;
	
	public VehicleModel(String brand, String model, int mileage, boolean newCondition, boolean warrentyStatus, int doorNumber) {
		this.brand = brand;
		this.model = model;
		this.mileage = mileage;
		this.newCondition = newCondition;
		this.warrentyStatus = warrentyStatus;
		this.doorNumber = doorNumber;
	}
	
	public VehicleModel(String brand, String model, int mileage, int doorNumber) {
		this.brand = brand;
		this.model = model;
		this.mileage = mileage;
		this.doorNumber = doorNumber;
	}
	
	public VehicleModel(String brand, String model, int mileage) {
		this.brand = brand;
		this.model = model;
		this.mileage = mileage;
	}

	/**
	 * @return the brand
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * @param brand the brand to set
	 */
	public void setBrand(String brand) {
		this.brand = brand;
	}

	/**
	 * @return the model
	 */
	public String getModel() {
		return model;
	}

	/**
	 * @param model the model to set
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * @return the mileage
	 */
	public int getMileage() {
		return mileage;
	}

	/**
	 * @param mileage the mileage to set
	 */
	public void setMileage(int mileage) {
		this.mileage = mileage;
	}

	/**
	 * @return the newCondition
	 */
	public boolean isNewCondition() {
		return newCondition;
	}

	/**
	 * @param newCondition the newCondition to set
	 */
	public void setNewCondition(boolean newCondition) {
		this.newCondition = newCondition;
	}

	/**
	 * @return the warrentyStatus
	 */
	public boolean isWarrentyStatus() {
		return warrentyStatus;
	}

	/**
	 * @param warrentyStatus the warrentyStatus to set
	 */
	public void setWarrentyStatus(boolean warrentyStatus) {
		this.warrentyStatus = warrentyStatus;
	}

	/**
	 * @return the doorNumber
	 */
	public int getDoorNumber() {
		return doorNumber;
	}

	/**
	 * @param doorNumber the doorNumber to set
	 */
	public void setDoorNumber(int doorNumber) {
		this.doorNumber = doorNumber;
	}

	@Override
	public String toString() {
		return "VehicleModel [brand=" + brand + ", model=" + model + ", mileage=" + mileage + ", newCondition="
				+ newCondition + ", warrentyStatus=" + warrentyStatus + ", doorNumber=" + doorNumber + "]";
	}

	
	
	
	
=======
/**
 * @author Chase Van Blair - crvanblair
 * CIS175 - Fall 2021
 * Feb 28, 2022
 */
package model;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="ModelTable")

public class VehicleModel extends Vehicle{
	//will be an entity
	//autogenerated id
	@Id
	@GeneratedValue
	@Column(name="ID")
	private int id;
	
	//specific name ex: ford (fusion)
	@Column(name="Model")
	private String model;
	
	//specific brand ex: (ford) fusion
	@Column(name="Make")
	private String make;
	
	//all wheel 4wd etc
	@Column(name="DriveTrain")
	private String driveTrain;
	
	//base sticker price of vehicle
	@Column(name="Price")
	private double price;
	
	//not sure if should inherit/extend the Vehicle class or just take it as param like this
	@Column(name="DateAdded")
	private LocalDate addedToLot;

	//TODO implement a way to hold the date/time of this added to warehouse? as a way for the time conversion requirement
	public VehicleModel() {

	}
	public VehicleModel(String model, String make, String driveTrain, double price, LocalDate addedToLot) {
		this.model = model;
		this.make = make;
		this.driveTrain = driveTrain;
		this.price = price;
		this.addedToLot = addedToLot;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	public String getMake() {
		return make;
	}
	public void setMake(String make) {
		this.make = make;
	}
	public String getDriveTrain() {
		return driveTrain;
	}
	public void setDriveTrain(String driveTrain) {
		this.driveTrain = driveTrain;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public LocalDate getAddedToLot() {
		return addedToLot;
	}
	public void setAddedToLot(LocalDate addedToLot) {
		this.addedToLot = addedToLot;
	}



>>>>>>> f329f712ef1e7eea959d66b14457145ee3e105d8:CarDealership/src/model/VehicleModel.java
}
