/**
 * @author Chase Van Blair - crvanblair
 * CIS175 - Fall 2021
 * Feb 28, 2022
 */
package model;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="ModelTable")

public class VehicleModel extends Vehicle{
	//will be an entity
	//autogenerated id
	@Id
	@GeneratedValue
	@Column(name="ID")
	private int id;
	
	//specific name ex: ford (fusion)
	@Column(name="Model")
	private String model;
	
	//specific brand ex: (ford) fusion
	@Column(name="Make")
	private String make;
	
	//all wheel 4wd etc
	@Column(name="DriveTrain")
	private String driveTrain;
	
	//base sticker price of vehicle
	@Column(name="Price")
	private double price;
	
	//not sure if should inherit/extend the Vehicle class or just take it as param like this
	@Column(name="DateAdded")
	private LocalDate addedToLot;

	//TODO implement a way to hold the date/time of this added to warehouse? as a way for the time conversion requirement
	public VehicleModel() {

	}
	public VehicleModel(String model, String make, String driveTrain, double price, LocalDate addedToLot) {
		this.model = model;
		this.make = make;
		this.driveTrain = driveTrain;
		this.price = price;
		this.addedToLot = addedToLot;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	public String getMake() {
		return make;
	}
	public void setMake(String make) {
		this.make = make;
	}
	public String getDriveTrain() {
		return driveTrain;
	}
	public void setDriveTrain(String driveTrain) {
		this.driveTrain = driveTrain;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public LocalDate getAddedToLot() {
		return addedToLot;
	}
	public void setAddedToLot(LocalDate addedToLot) {
		this.addedToLot = addedToLot;
	}



}
